### PR TITLE
point selection

### PR DESCRIPTION
**Pull request by by408**

### CODE REVIEW

**Comment by oleg-alexandrov** [comment]
I fetched the contribution [c3a548f](https://github.com/oleg-alexandrov/PolyView/pull/2/commits/c3a548f6fd3e85536606baf6845b87ad0bf3fe09). But not the large xg file.

**Comment by oleg-alexandrov** [comment]
BTW, your fork and mine diverged now. You can add my remote as described here: https://www.atlassian.com/git/tutorials/git-forks-and-upstreams (this won't change anything, it just lets you see my repo alongside your fork). Then the command "git reset --hard <comit id>" can be used to ensure one repo is reset to be a perfect miror of the other one. This wipes any divergent and local changes.

**Comment by oleg-alexandrov** [comment]
This is also very useful: https://coderwall.com/p/euwpig/a-better-git-log

**Comment by by408** [comment]
Nice

Bayram

On Oct 9, 2022, at 11:47 AM, Oleg Alexandrov ***@***.***> wrote:

﻿
This is also very useful: https://coderwall.com/p/euwpig/a-better-git-log

**Pull request closed without merging**
