### PR TITLE
All changes are tested

### PR DESCRIPTION
**Pull request by by408**
I added grayscale image support with color map. And updated the documentation with the new features. Feel free to improve it.

### CODE REVIEW

**Comment by oleg-alexandrov** [comment]
Looks good. Thanks. 

I made a small change to the documentation to not mention cmake, as that build modality is not used currently and likely is out of date. Only qmake is supported.

**Comment by oleg-alexandrov** [comment]
I made a few more very minor doc edits.

**Comment by by408** [comment]
I had to use cmake to compile on one of our isolated servers that did not have proper qmake installation. BayramOn Oct 8, 2023, at 3:38 PM, Oleg Alexandrov ***@***.***> wrote:﻿
Looks good. Thanks.
I made a small change to the documentation to not mention cmake, as that build modality is not used currently and likely is out of data. Only qmake is supported.

**Comment by oleg-alexandrov** [comment]
Good point. The issue is that cmake compilation is not documented, in the
section above where compilation is described, and then just having that
line about cmake would look out of place. I did not actually remove that
line about openmp from the CmakeLists file, so for now all this is
unsupported and undocumented, but likely still works.

As I recall, qmake was working better than cmake at finding Qt's OpenGL
dependencies, before one introduced the (now optional) OpenMP option.

**Comment by by408** [comment]
That is a valid point, for now you can remove cmake openmp partBayramOn Oct 8, 2023, at 4:20 PM, Oleg Alexandrov ***@***.***> wrote:﻿
Good point. The issue is that cmake compilation is not documented, in the

section above where compilation is described, and then just having that

line about cmake would look out of place. I did not actually remove that

line about openmp from the CmakeLists file, so for now all this is

unsupported and undocumented, but likely still works.



As I recall, qmake was working better than cmake at finding Qt's OpenGL

dependencies, before one introduced the (now optional) OpenMP option.







On Sun, Oct 8, 2023 at 3:52 PM Bayram Yenikaya ***@***.***>

wrote:

**Pull request merged**
